### ISSUE TITLE
FsCheck unit tests broken by F# 4.1: "Unable to cast object of type 'XXX' to type 'Testable ...`"

### ISSUE THREAD

**Issue by blumu** [Microsoft/fsharplu#14]
Four FsCheck-based unit tests are now failing after the upgrade to F# 4.1. This was not caught in the continuous builds because the build definition defaulted to VS 2015 and F# 4.0 even though the the .fsproj files specifically require F# 4.1.

The affected unit tests are:
```
    member this.``Serialization and deserialization are reciprocal``() =
    member __.``Fuzzing Reciprocal`` () =
    member __.``Deserialization coincides with JSon.Net (Fuzzing)`` () =
    member __.``BackwardCompatible deserializes default Json.Net format and returns same object`` () =
```

Call stack for the `BackwardCompatible` test:
```
Test method Microsoft.FSharpLu.Json.Tests+JsonSerializerTests.BackwardCompatible deserializes default Json.Net format and returns same object threw exception: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: BackwardCompatibility.get_x1-Falsifiable, after 1 test (0 shrinks) (StdGen (1333139700,296279097)):
Original:
<null>
with exception:
System.InvalidCastException: Unable to cast object of type 'Arrow@202-1[Microsoft.FSharpLu.Json.Tests+ComplexDu,Microsoft.FSharp.Core.Unit]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharpLu.Json.Tests+ComplexDu,Microsoft.FSharp.Core.Unit]]'.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 151
```

**Comment by blumu** [comment]
Bumping up the F# version in app.config for the unit test project fixed 1 out of 4 failing unit tests. I'm still getting the following exception though. It may just be an incompatibility with F# 4.1 rather than FsCheck:
```
Message: Test method Microsoft.FSharpLu.Json.Tests+JsonSerializerTests.BackwardCompatible deserializes default Json.Net format and returns same object threw exception: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: BackwardCompatibility.get_x13-Falsifiable, after 1 test (0 shrinks) (StdGen (2021048758,296279401)):
Original:
<null>
Leaf []
with exception:
Newtonsoft.Json.JsonSerializationException: Cannot create and populate list type Microsoft.FSharp.Collections.FSharpList`1[System.Int32]. Path '', line 4, position 5.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.FSharpLu.Json.Default.deserialize[T](String json) in D:\sources\FSharpLu\FSharpLu.Json\NewtonSoft.fs:line 45
   at Microsoft.FSharpLu.Json.Tests.get_x13@147-5.Invoke(Tree`1 x) in D:\sources\FSharpLu\FSharpLu.Tests\JsonTests.fs:line 147
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 161
```

**Comment by blumu** [comment]
It's an incompatibility in Newtonsoft JSon.Net. Bug already filed for it at https://github.com/JamesNK/Newtonsoft.Json/issues/1180
